include:
  - ../3d-printer/recipe-per-flavor/ingredients/core.yaml
  - ../3d-printer/recipe-per-flavor/ingredients/mosquitto.yaml
  - ../3d-printer/recipe-per-flavor/ingredients/octoprint-marlin.yaml
  - ./temperature-simulation-sidecar.yaml
