services:
  3d-printer-viewer:
    build: ../../../src/3d-printer-viewer
    restart: unless-stopped
    ports:
      - 8000:8000

  telegraf:
    image: telegraf
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094
    restart: unless-stopped
    volumes:
      - ../../../telegraf-config.toml:/etc/telegraf/telegraf.conf

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: octoPrint
    ports:
      - 5432:5432
    volumes:
      - ../../../docker-data/postgresql/data:/var/lib/postgresql/data
      - ../../../src/postgres-init:/docker-entrypoint-initdb.d:ro

  influxdb:
    image: influxdb:3-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - ../../../docker-data/influxdb3/data:/var/lib/influxdb3/data
      - ../../../docker-data/influxdb3/plugins:/var/lib/influxdb3/plugins

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "0"
    ports:
      - 3000:3000
    volumes:
      - ../../../docker-data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
    depends_on:
      - timescaledb
